# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 967f5f27ff4dca5d09ca5fdd7070c3597e618c569014160fbd15a8e7b6b2cdc54ffbe0ce2bcb80413a30a6a84b2a0438005f566549cbcb5dc1bf8946b5c3389f

test:
  secret_key_base: cc407f4b6b02591a678408900b41f2f015ef9604e18ce6cc50c0e5902cab2cea01ee6aa4ccf3bb895e81e8cf0630f8b927555c0cafea5350ef96e937dd8798db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
